### ISSUE TITLE
macro expansion in eigency_cpp.h

### ISSUE THREAD

**Issue by neok-m4700** [wouterboomsma/eigency#10]
In Eigen 3.3.3, the macro EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION expands to either Eigen::RowMajor or Eigen::ColMajor as has been introduced by this [commit](https://bitbucket.org/eigen/eigen/commits/5f52a5f56992f5890ff3effd03c9e6ddb30487d2)

But in eigency, in eigen_cpp.h, DenseBase is templated using Eigen::EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION, which after expansion yields a 

```bash
error: ‘Eigen::Eigen’ has not been declared
 #define EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION Eigen::ColMajor 
```

a workaround when building eigency with eigen 3.3.3 will be 

```bash
sed -i 's,Eigen::EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION,EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION,' eigency/eigency_cpp.h

python setup.py install
```

Thanks again for this amazing extension

**Comment by wouterboomsma** [comment]
Thanks for reporting this. I added a preprocessor check on the version where it was introduced, so it should now behave properly for all versions. Could you just verify that it works for you? I pushed and also released a new version to pypi. Thanks.

**Comment by neok-m4700** [comment]
Yep, eveything working fine. The other patch on the testsuite is also working.

closing :+1: 

thanks for the reactivity !
