### ISSUE TITLE
Release tarball 1.74 does not include eigen source code

### ISSUE THREAD

**Issue by sebp** [wouterboomsma/eigency#13]
The archive [eigency-1.74.tar.gz](https://pypi.python.org/packages/9a/46/db59a9c09b3b4f684917edb58f24daef49463b25811989156984b8147279/eigency-1.74.tar.gz#md5=460575838955a06496a5629ee33c0a0d) does not contain the `eigency/eigen_3.2.8` directory, therefore the build fails.

I might have missed something in #12, although running `python setup.py sdist` locally gives the expected result for me.

**Comment by wouterboomsma** [comment]
Hmm, so I pushed the new release too quickly after all. I should have noticed the large difference in size between the 1.73 and 1.74 tar balls. 

If I issue the ```python setup.py sdist``` locally I get the same behavior - a small tar.gz file with no eigen included. Did you do this from a clean checkout?

**Comment by wouterboomsma** [comment]
It seems that `package_data` is only included with binary packages, not in source packages.

**Comment by wouterboomsma** [comment]
Sorry...just trying to refresh my memory - it is the MANIFEST.in that controls the contents of the source package. In the old version, we had an explicit `recursive-include eigen_3.2.8 *`. You made some changes here, I guess partially as a consequence of moving the `eigen_3.2.8` directory into the `eigency` directory. Before I spend more time on this, could you just try again if you can reproduce the problem locally? Thanks.

**Comment by sebp** [comment]
Which python and setuptools version are you using so I can try to reproduce the problem?

**Comment by wouterboomsma** [comment]
```
$ python --version
Python 2.7.12 :: Continuum Analytics, Inc.
$ python -c "import setuptools; print setuptools.__version__"
34.3.0
```
