### ISSUE TITLE
how to specify eigency dependency before setup.py ? 

### ISSUE THREAD

**Issue by lacava** [wouterboomsma/eigency#16]
Thanks for this awesome package. I'm wondering if there is a way around having `import eigency` in the setup.py file for my project, since setup.py will fail if eigency is not installed, even with `install_requires=['eigency']` specified (i'm using setuptools here).

**Comment by lacava** [comment]
nvm, setup_requires is what i was looking for!

**Comment by lacava** [comment]
actually, adding `setup_requires = ['eigency']` does not appear to fix the issue. do you have any recommendations for addressing the import of eigency in the setup.py file?

**Comment by wouterboomsma** [comment]
Thanks for reporting this. I haven't stumbled onto this problem before, so I don't have any solid recommendations here, but it is probably relevant for other eigency users as well, so it would be good to find a working solution. In the few issue you added a  [link](https://mail.python.org/pipermail/distutils-sig/2015-March/025882.html) to a discussion which suggests subclassing. I assume the broken link on that last page should have referred to [this page](https://docs.pytest.org/en/latest/goodpractices.html#manual-integration). Have you tried this approach? 

There might also be a way to get around the `import eigency` alltogether. Its only role is to provide the necessary include directories to the parent Extension. Perhaps there is a different way to pass along this information?

**Comment by lacava** [comment]
the following solution (commit b4b97d0dd43192848407bce4aa3eb8f6779b456f) works if the user is using pip. it adds code to setup.py to try to manually install eigency in setup.py using pip, reporting an error if it fails: 

```python
# the setup file relies on eigency to import its include paths for the
# extension modules. however eigency isn't known as a dependency until after
# setup is parsed; so we need to check for and install eigency before setup.
import importlib
try:
    importlib.import_module('eigency')
except ImportError:
    try:
        import pip
        pip.main(['install', 'eigency'])
    except ImportError:
        raise ImportError('The eigency library must be installed before FEW. '
                          'Automatic install with pip failed.')
finally:
    globals()['eigency'] = importlib.import_module('eigency')
```

**Comment by wouterboomsma** [comment]
Thanks for following up on this. A bit depressing that one has to resolve to calling pip explicitly, but certainly better than no solution. Closing.
