### ISSUE TITLE
Installing eigency without cython

### ISSUE THREAD

**Issue by tasptz** [wouterboomsma/eigency#28]
https://github.com/wouterboomsma/eigency/blob/aae9801fa9034d1ff0ab57dfd56a0338d984ed13/setup.py#L28

I get the error `c1xx: fatal error C1083: Cannot open source file: 'eigency/conversions.cpp': No such file or directory`, when trying to install the package without having cython installed.

**Comment by philastrophist** [comment]
This happens with or without cython

**Comment by ffcccc** [comment]
I got the same error installing from anaconda terminal (win10 +python 3.6) without admin rights.
After that:
-restarted navigator and terminal as admin
-installed cython (probably not needed) successfully
-installed eigency successfully
Good luck

**Comment by tanujdhiman** [comment]
Thanks @ffcccc It resolved !!

**Comment by BTOdell** [comment]
PR #27 (just merged) should fix this. I will leave this issue open until I spin a new release on Pypi.

**Comment by BTOdell** [comment]
1.78 has been released on PyPi and should fix this problem.
