### ISSUE TITLE
Possiblity to use long double as type

### ISSUE THREAD

**Issue by CarloNicolini** [wouterboomsma/eigency#29]
Currently there is no possibility to map long double matrices to numpy.
Any idea how to do it?

This would be very beneficial to all users as very often matrix exponentials as computed by Eigen benefit a lot of large precision.

**Comment by BTOdell** [comment]
As long as both Eigen and numpy have `long double` support, I don't see a reason why this couldn't be added.

**Comment by BTOdell** [comment]
https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.longdouble
