### ISSUE TITLE
Outdated Eigen Library

### ISSUE THREAD

**Issue by InspireX96** [wouterboomsma/eigency#31]
Hi, I found some compile error when trying to wrap some Eigen 3.3 functions. Solved the problem by replacing the Eigen 3.2.8 Library in this package to Eigen 3.3.7 and it worked in my case. I am not sure if you are still updating this package, but it would be nice if you can update the Eigen library here. Thanks!

**Comment by hwiedDFKI** [comment]
It would be very nice if it would just use the system eigen ;)
I replaced eigen by a submodule of the eigen git mirror...

**Comment by hwiedDFKI** [comment]
Please see #36

**Comment by BTOdell** [comment]
Upgrading Eigen (and potentially supporting multiple versions) is planned and tracked in the Eigency Roadmap #42
