### ISSUE TITLE
unable to pass empty matrix eigen to numpy

### ISSUE THREAD

**Issue by fbordeu** [wouterboomsma/eigency#38]
Hello,

A have a code in c++ that compute a variable size vector. then this vector is send using eigency to python.
For some data the algorithm create an empty vector, then when a tried to send this empty vector to python I get the following message:

        return  ndarray(self.dn_cpp.ComputeVectorSometimeEmptyVector())
      File "eigency/conversions.pyx", line 67, in eigency.conversions.ndarray_long_F
    ValueError: Cannot create cython.array from NULL pointer

The problem is that at the cython level I have only a PlainObjectBase, with no possibility to test the size (rows() and cols()) to handle this situation correctly.

Any ideas on how can treat this problem.

Felipe

**Comment by BTOdell** [comment]
What is the return type of `ComputeVectorSometimeEmptyVector`? Can it return a null pointer?
The `eigency.conversions.ndarray_long_F` function assumes that the data pointer is not null.

I'm not sure what you mean by "at the cython level I have only a PlainObjectBase". Where are you getting this PlainObjectBase from?

**Comment by BTOdell** [comment]
Confirmed that Eigen has a `null` matrix that does not allocate:
```c++
#include <iostream>
#include <Eigen/Dense>
 
using Eigen::MatrixXd;
 
int main()
{
  MatrixXd m(2,2);
  std::cout << m.data() << std::endl;
  MatrixXd n;
  std::cout << n.data() << std::endl;
}
```

Output:
```
0x1405eb0
0
```
