### ISSUE TITLE
Mapping a list of Numpy matrices to a vector of Eigen matrices fails

### ISSUE THREAD

**Issue by Stefan-1313** [wouterboomsma/eigency#39]
I have a C++ function which I want to run from Python. For this I use Cython.
My C++ function relies heavily on Eigen matrices which I map to Python's Numpy matrices using Eigency.

I cannot get this to work for the case where I have a list of Numpy matrices.

----------

**What does works (mapping a plain Numpy matrix to an Eigen matrix):**

I have a C++ function which in the header (Header.h) looks like:

    float MyCppFunction(Eigen::Map<Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>> &inputMatrix)

In my CythonFile.pyx file I have (and create the maps using Eigency as explained [here][1]):

    cdef extern from "Header.h":
        cdef void _MyCppFunction "MyCppFunction"(FlattenedMapWithOrder[Matrix, float, Dynamic, Dynamic, RowMajor] &)

and

    def my_python_function(np.ndarray[ndim=2, dtype=np.float32_t] my_matrix)
        return _MyCppFunction(FlattenedMapWithOrder[Matrix, float, Dynamic, Dynamic, RowMajor](my_matrix))

I can build this module using Cython and call `my_python_function` successfully from Python.

----------

**What does not work (mapping a list of Numpy matrices to a vector of Eigen matrices):**

Now I try to do the same thing, but for a list of matrices. I cannot get this to work.
What I have:

The C++ function in the header (Header.h) looks like:

    float MyCppFunction(std::vector<Eigen::Map<Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>>> &inputMatrixList)

In my CythonFile.pyx file I have:

    cdef extern from "Header.h":
        cdef void _MyCppFunction "MyCppFunction"(vector[FlattenedMapWithOrder[Matrix, float, Dynamic, Dynamic, RowMajor]] &)

and

    def my_python_function(list my_matrix_list)
		cdef vector[FlattenedMapWithOrder[Matrix, float, Dynamic, Dynamic, RowMajor]] map
		
		for matrix in my_matrix_list:
			map.push_back(FlattenedMapWithOrder[Matrix, float, Dynamic, Dynamic, RowMajor](matrix))
			
	   return _MyCppFunction(map)

This won't compile unfortunately.

This concept does compile and run when I, for example, simply use a `list` of `int` which I want to map to a `std::vector<int>`. It does not work however, when I map a list of Numpy-matrices to a vector of Eigen matrices (which is the case I have denoted above).

----------

**The Error I get:**

The error I get during compilation:
`error C2664: 'void MyCppFunction(std::vector<Eigen::Map<Eigen::Matrix<float,-1,-1,1,-1,-1>,0,Eigen::Stride<0,0>>,std::allocator<Eigen::Map<Eigen::Matrix<float,-1,-1,1,-1,-1>,0,Eigen::Stride<0,0>>>> &)': cannot convert argument 1 from 'std::vector<eigency::FlattenedMap<Eigen::Matrix,float,-1,-1,1,0,0,0,-1,-1>,std::allocator<eigency::FlattenedMap<Eigen::Matrix,float,-1,-1,1,0,0,0,-1,-1>>>' to 'std::vector<Eigen::Map<Eigen::Matrix<float,-1,-1,1,-1,-1>,0,Eigen::Stride<0,0>>,std::allocator<Eigen::Map<Eigen::Matrix<float,-1,-1,1,-1,-1>,0,Eigen::Stride<0,0>>>> &'
./Header.h(21): note: see declaration of 'MyCppFunction'`

----------

**My analysis so far:**

This works as expected, so: I can assign a python `list` of `int` to a C++ `std::vector<int>`.

This works also as expected, so: I can assing a variable of type `eigency::FlattenedMap<Eigen::Matrix,float,-1,-1,1,0,0,0,-1,-1>` to a variable of type `Eigen::Map<Eigen::Matrix<float,-1,-1,1,-1,-1>,0,Eigen::Stride<0,0>>`.

When I wrap the latter two variables in a list/vector, then I cannot assign these two variables:
`std::vector<eigency::FlattenedMap<Eigen::Matrix,float,-1,-1,1,0,0,0,-1,-1>, std::allocator<eigency:...>` to a variable of type `std::vector<Eigen::Map<Eigen::Matrix<float,-1,-1,1,-1,-1>,0,Eigen::Stride<0,0>>, std::allocator<Eigen:...>`.

Maybe it has to do with the allocator part but I don't know since I'm not really a C++ expert.
Does anybody has a solution to map a list of Numpy matrices to a vector of Eigen matrices? Preferably, following the same patterns as above but other solutions are also welcome.

----------

Thank you very much!

  [1]: https://pypi.org/project/eigency/1.4/

**Comment by BTOdell** [comment]
This behavior will exist in most languages with generics/template support.
Essentially, just because type `FlattenedMap` can be assigned to type `Map`, doesn't mean that `std::vector<FlattenedMap>` can be assigned to `std::vector<Map>`.

Consider this (assuming B is a subtype of A and another type C is also a subtype of A):
```c++
std::vector<B> vB;
std::vector<A>& vA = vB;
vA.push_back(C());
```

If the compiler allowed this kind of code to compile, then `vB` would now contain an object of type `C` even though it's a vector of `B`.

Additional reading: https://docs.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance

My suggestion would be to update your C++ header code so the `MyCppFunction` accepts a `FlattenedMap` vector instead of a `Map` vector.

**Comment by Stefan-1313** [comment]
Thank you!
I indeed figured this out a while ago and got it working in a way similar as you describe.
For future readers, here is how I got it working: https://stackoverflow.com/questions/69584633/how-to-map-a-list-of-numpy-matrices-to-a-vector-of-eigen-matrices-in-cython/70189527#70189527

And thanks for the reading! Always good to formalize some of the 'simple' things you know from experience but there can still be a lot behind it.

**Comment by BTOdell** [comment]
Thank you for posting that Stackoverflow link!

At the bottom you mention that the `eigency_cpp.h` is not "self-contained" which is a reported issue in PR #40 that I've been looking to verify. And it looks like the guy who was helping you on Stackoverflow is the author of that PR. It's like piecing a puzzle together 😄 

I'm not sure if you're still using this project, but I'll merge in that PR and release 1.79 so that the headers are self-contained.

**Comment by Stefan-1313** [comment]
Thanks! I use eigency once in a while. So it will be great to have this for future projects :D.
Yeah, that guy on SO helped me a lot. Without doing it on purpose, I sort of verified that the additions in the SO post made the header work, so including them in the header should make it self contained. So if the PR contains the same, you can merge it without problems.

Thanks for your great project!
