### ISSUE TITLE
 multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_view<double>(double*, long, long, bool, long, long)

### ISSUE THREAD

**Issue by code-ball** [wouterboomsma/eigency#4]
Hi,

First, Thank you so much for creating this library. It is an extremely useful tool for Cython users.

Now, I was trying to use basic vector and matrix functions in my test C++ wrapping project for cython. 
But when I compile my code, I get the following error:

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_view<double>(double*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:27: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_view<double>(double*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:27: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_copy<double>(double const*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:39: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_copy<double>(double const*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:39: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_view<float>(float*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:47: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_view<float>(float*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:47: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_copy<float>(float const*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:54: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_copy<float>(float const*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:54: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_view<long>(long*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:62: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_view<long>(long*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:62: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_copy<long>(long const*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:69: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_copy<long>(long const*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:69: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_view<int>(int*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:77: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_view<int>(int*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:77: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_copy<int>(int const*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:84: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_copy<int>(int const*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:84: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_view<short>(short*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:92: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_view<short>(short*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:92: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_copy<short>(short const*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:99: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_copy<short>(short const*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:99: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_view<char>(char*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:107: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_view<char>(char*, long, long, bool, long, long)'
> build/temp.linux-x86_64-3.4/cytest2.o:/usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:107: first defined here

> build/temp.linux-x86_64-3.4/cytest.o: In function `tagPyArrayObject_fields* eigency::_ndarray_copy<char>(char const*, long, long, bool, long, long)':
> /usr/local/lib/python3.4/dist-packages/eigency/eigency_cpp.h:114: multiple definition of `tagPyArrayObject_fields* eigency::_ndarray_copy<char>(char const*, long, long, bool, long, long)'

I have two files pyx file cytest.pyx and cytest2.pyx. cytest imports cytest2 to use functions defined there. But both cytest and cytest2 requires to use eigency library and hence I have from eigency.core import * in both files.

I have written the setup file as you have suggested in readme and it is able to locate eigency library.

Can you suggest why this is happening?

Thanks

**Comment by wouterboomsma** [comment]
Hi,

Thanks. Not sure exactly what is going wrong here. But are you sure that you need the `from eigency.core import *` in the `cytest.pyx` file? The eigency symbols symbols should already be available through cytest2 (although you might have to access them with a `cytest2.` prefix, or explicitly import all symbols directly using `from cytest2 import *`.
If you attach a zip/tar.gz containing a complete minimal example that fails with these errors, I could certainly take a closer look.

**Comment by code-ball** [comment]
Hi,

I have been able to replicate the problem by modifying the provided example in **tests** folder here. I have modified the code to exemplify the requirement of my code and hence it will be easy for you to see the issue. I am able to see that the issue is not `from eigency.core import *` in multiple files. Rather in my case, the issue happens due to multiple .pyx files trying to use functions declared in common header file

Please check the attached zip file. Following are major changes in code I made:

- I have created a new eigency_tests.pxd file for containing header definitions and moved all function from .h files there.
- In eigency_tests.pyx, I am doing `from eigency_tests cimport _FixedMatrixClass, _DynamicArrayClass, _DynamicRowMajorArrayClass  ` for getting all class information from header files.
- In eigency_tests.pyx, I changed one of class names from FixedMatrixClass to testClass. One can actuaully use any class names here as it is not dependent on any C++ code.
- I have created another .pyx file eigency_tests2.pyx whose code is as follows 

```python
from eigency_tests cimport _FixedMatrixClass
from eigency_tests import testClass
#from eigency.core import *
def test():
    test_obj = testClass()
    d = test_obj.get_matrix()
    pass
```
Commenting or not commenting the `#from eigency.core import *` does not affect any thing and still creates error.

But the error resolves if I change cimport to import in the line `from eigency_tests cimport _FixedMatrixClass`

So, the thing is it does not allow me to cimport functions defined in header file to multiple .pyx files. 
This generally does not give any error when I do not use eigency.

Please note: this error happen during compilation for run_tests.py can be ignored.

Please let me know if you can find a solution or explain me if I am incorrect somewhere.

Thank you very much for helping me out.
[test_files.zip](https://github.com/wouterboomsma/eigency/files/400344/test_files.zip)

**Comment by wouterboomsma** [comment]
Hi,
Sorry for the very long delay on this issue. Vacation and teaching preparation got in the way. 
Thanks for preparing a nice minimal example. This made it very clear what was going wrong. The error was due to some of the C++ functions not being declared with the `inline` keyword. I just pushed a new version that fixed it. The example you sent now compiles.

**Comment by wouterboomsma** [comment]
@code-ball, I'm closing this issue now - since the changes I made seem to have resolved the problem. In case you still experience problems, feel free to comment or open a new issue.
