### ISSUE TITLE
there is not complex conversions nor copy

### ISSUE THREAD

**Issue by trago** [wouterboomsma/eigency#5]
Is there any chance to implement complex conversion to  deal with complex types?

**Comment by wouterboomsma** [comment]
Hi
I've just pushed a version which should deal with complex numbers. In the tests directory there is now a test called`function_w_complex_mat_arg` that demonstrates the behaviour on a very simple test case. I must admit that I haven't had time to test this functionality very thoroughly, so it would be good to get some feedback on whether it works.

**Comment by trago** [comment]
Hi, thank you!!

Sure, I will be testing
