### ISSUE TITLE
Map SparseMatrix?

### ISSUE THREAD

**Issue by syoh** [wouterboomsma/eigency#56]
Hello,

Thank you for a great package and set of examples!

I want to use eigency to build a package, and I learned from/modified the code in tests to do most of what I need to do.

I haven't been able to figure out if I use eigency to map Eigen SparseMatrix from Python. Is that possible? If so, where can I find an example?

Thanks for any pointers!

**Comment by BTOdell** [comment]
I think Eigency supports all types of matrices. You just have to specify the `MatrixType` when you instantiate the `Map` type. I could be wrong though. I would try to adapt the existing examples using a different matrix type.
