### ISSUE TITLE
Solving sparse matrix equation

### ISSUE THREAD

**Issue by liyingyinsimon** [wouterboomsma/eigency#62]
I am currently using python.
I would like to ask is there any function to use in eigency for solving sparse matrix equation? If yes, is there a GPU support version also? Is there documentation to see what functions I can call in eigency?

Thank you.

**Comment by BTOdell** [comment]
Sorry for the delay.

There is no GPU support provided by eigency.
The only documentation provided is available in the README: https://github.com/wouterboomsma/eigency/blob/master/README.md#usage
